# Base configs
baseurl: "https://joshuasrcho.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Joshua Cho"
subtitle: "See the world through my eyes!"
author: "Joshua Cho"
header:
 title: "Photography"
 subtitle: "by Joshua Cho"
footer:
 name: "Hey there, my name is Joshua"
 bio: "I am a robotics engineer from Los Angeles, CA. When I'm not busy tinkering with robots, I'm out exploring with my camera. Discover the world through my lens."
#  github:
web_design:
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/sr_cho_"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
